### PR TITLE
Add the head.py file to track and use the HEAD object.

### PR DESCRIPTION
**Pull request by SidZRed**
Added the basic functionalities of the `head` object.
Will create another file in `/commands` to implement the functionalities of the `head` object.

Someone kindly also add the import and initialisation of this object in the Init

### CODE REVIEW

**Comment by DhruvaKashyap** [comment]
Wouldn't you be storing the HEAD somewhere?
I don't see where you would be using the history. sfit is intended to be a command, not a running application, if that makes sense.

**Comment by SidZRed** [comment]
> Wouldn't you be storing the HEAD somewhere?

Yes we would store it somewhere.
> I don't see where you would be using the history. sfit is intended to be a command, not a running application, if that makes sense.

It would be the same thing even if you snapshot head everytime and use it from there or here so for checking something like log, I thought it would be easier to store it as a property of the head itself.
It also becomes easier if we are implementing something like head^ or head~

**Comment by kevalpithadiya** [comment]
This is not how `HEAD` is supposed to be implemented. There is not much point in having a Python object represent `HEAD`. `HEAD` is simply a file which points to the currently active branch.

You have to understand how this program is supposed to be used. You run the program by giving a specific command with arguments and every time this happens, the program runs from the start. If the command run requires reading / modifying  `HEAD`, we directly use functions to read / write to the file. These can be simple helper functions defined in a file in `utils`.

**Comment by SidZRed** [comment]
No, now my intention was to have a helper object to control the functionalities of the head. Then we would have a file which stores the value (reference path) after each command. So there would be another function which would use this object to write to the HEAD file each time.
Even if you don't have this, you would have to have separate functions to write to that head object (file). So I felt it would be easier if we have a (class) object controlling how they are functioning.
Ok, I will change how all this is implemented by accessing the head file instead.

I will make some changes to show what I want to do using this. I did not intend it to be a running application and have the head object store the data with itself.

**Comment by kevalpithadiya** [comment]
See, `HEAD` by itself does not have any functionality. `HEAD` is simply a data structure (if it even qualifies that definition).

It is simply supposed to be a pointer to the currently active branch. The functionality is implemented by the command_handler functions for each command by interpreting the data stored in `HEAD` in the appropriate manner.

As Dhruva hinted, having a class represent the `HEAD` makes sense if this was supposed to be a running program where you repeatedly need to refer to (changing) information associated with the `HEAD`.

Perhaps we can discuss this in person to clear up any misunderstandings.

**Comment by SidZRed** [comment]
Ok sure, I get it that the `HEAD `by itself does not need to have any functions, but these functions are rather to modify/ do something with the `HEAD `object. It is the same thing to implement this in a command_handler file but since it had a few functions , I thought it would be easier to import this to the command_handler file for functionalities of `HEAD `and use them there directly.
So anything is fine, either directly writing these functions there / importing this to implement them over there.

**Comment by DhruvaKashyap** [comment]
I think having the HEAD helpers is a good idea, but I don't see how history will ever be more than a single item, unless you intend to store everywhere your HEAD has ever been. Which doesn't seem to be useful.

**Comment by SidZRed** [comment]
Should be fine now I think. I have added a new implementation.
I understood why it was weird to have the history thing and that seems to have caused a lot of confusion. My bad, I was thinking about something totally different with that unrelated to this. So now I think it looks like what can be implemented for a single command.
Sorry for causing any confusions ! 

Commands will be implemented when we decide upon a common pattern to keep it consistent.

**Comment by DhruvaKashyap** [comment]
Some type annotations and this would be ready to go

**Review by kevalpithadiya — CHANGES_REQUESTED** [review]
The library `head.py` looks good to me. But please move it to `utils/head.py` since it is a utility file.

I don't think `head_cli.py` is necessary. Any command which requires the functionality of `head.py` will import and use `head.py` accordingly. Commands are implemented in `commands` folder.

**Comment by SidZRed** [comment]
Yeah I didn't add it to the commands folder since i didn't know the basic pattern in which all commands are being implemented and it would mess up the consistency.
I'll add it to the commands folder later, for now i will remove this file

**Review by kevalpithadiya — APPROVED** [review]
LGTM!

**Comment by DhruvaKashyap** [comment]
Still waiting for those type hints

**Pull request merged**
